import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import GlobalProvider from "./providers/GlobalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <div className="flex flex-col min-h-screen bg-gray-100">
            <Header />
            {children}
            <footer className="bg-black text-white py-8">
              <div className="container mx-auto grid grid-cols-2 md:grid-cols-4 gap-8">
                <div>
                  <h3 className="font-bold mb-4">Abstract</h3>
                  <ul>
                    <li>Branches</li>
                  </ul>
                </div>
                <div>
                  <h3 className="font-bold mb-4">Resources</h3>
                  <ul>
                    <li>Blog</li>
                    <li>Help Center</li>
                    <li>Release Notes</li>
                    <li>Status</li>
                  </ul>
                </div>
                <div>
                  <h3 className="font-bold mb-4">Community</h3>
                  <ul>
                    <li>Twitter</li>
                    <li>LinkedIn</li>
                    <li>Facebook</li>
                    <li>Dribbble</li>
                    <li>Podcast</li>
                  </ul>
                </div>
                <div>
                  <h3 className="font-bold mb-4">Company</h3>
                  <ul>
                    <li>About Us</li>
                    <li>Careers</li>
                    <li>Legal</li>
                  </ul>
                  <h3 className="font-bold mt-4 mb-2">Contact Us</h3>
                  <p>info@abstract.com</p>
                </div>
              </div>
              <div className="container mx-auto mt-8 flex justify-between items-center">
                <div className="w-8 h-8 bg-white rounded-full"></div>
                <p className="text-sm">
                  &copy; Copyright 2022
                  <br />
                  Abstract Studio Design, Inc.
                  <br />
                  All rights reserved
                </p>
              </div>
            </footer>
          </div>
        </GlobalProvider>
      </body>
    </html>
  );
}
